// <auto-generated />
using System;
using CA_TheaterDB_CodeFirst.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA_TheaterDB_CodeFirst.Migrations
{
    [DbContext(typeof(TheaterDBContext))]
    partial class TheaterDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.MovieCategory", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "CategoryID");

                    b.HasIndex("CategoryID")
                        .IsUnique();

                    b.HasIndex("MovieID")
                        .IsUnique();

                    b.ToTable("MovieCategories");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Saloon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("SaloonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Saloons");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Theater", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("SaloonID")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("WeekID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.HasIndex("SaloonID");

                    b.HasIndex("SessionID");

                    b.HasIndex("WeekID");

                    b.ToTable("Theaters");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Week", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("WakeFirstDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WakeLastDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeekName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.MovieCategory", b =>
                {
                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Category", null)
                        .WithOne("MovieCategory")
                        .HasForeignKey("CA_TheaterDB_CodeFirst.Entities.MovieCategory", "CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Movie", null)
                        .WithOne("MovieCategory")
                        .HasForeignKey("CA_TheaterDB_CodeFirst.Entities.MovieCategory", "MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Theater", b =>
                {
                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Movie", "Movie")
                        .WithMany("Theater")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Saloon", "Saloon")
                        .WithMany("Theater")
                        .HasForeignKey("SaloonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Session", "Session")
                        .WithMany("Theater")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA_TheaterDB_CodeFirst.Entities.Week", "Week")
                        .WithMany("Theater")
                        .HasForeignKey("WeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Saloon");

                    b.Navigation("Session");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Category", b =>
                {
                    b.Navigation("MovieCategory")
                        .IsRequired();
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Movie", b =>
                {
                    b.Navigation("MovieCategory")
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Saloon", b =>
                {
                    b.Navigation("Theater");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Session", b =>
                {
                    b.Navigation("Theater");
                });

            modelBuilder.Entity("CA_TheaterDB_CodeFirst.Entities.Week", b =>
                {
                    b.Navigation("Theater");
                });
#pragma warning restore 612, 618
        }
    }
}
